---

loki_apt_update_cache: True
loki_version: "2.6.1"
loki_dist_url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"
loki_checksum: "sha256:f9c577d54e35e5f46b1a9d0e0788299a0c1e69975ee999d27c3dc711942cc973"
loki_config_dir: /etc/loki
loki_storage_dir: /tmp/loki
loki_config_file: "{{ loki_config_dir }}/loki-local-config.yml"

loki_system_user: loki
loki_system_group: "{{ loki_system_user }}"
loki_systemd_service_template_file: service.j2
loki_systemd_service: loki

loki_install_dir: /opt/loki
loki_tmp_dir: /tmp


loki_listen_port: 3100
