{
 "title": "Production server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"Prod_servers\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"Prod_servers\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"Prod_servers\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{job=\"Prod_servers\"}) /  count(count(node_cpu_seconds_total{job=\"Prod_servers\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{job=\"Prod_servers\"}) /  count(count(node_cpu_seconds_total{job=\"Prod_servers\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"Prod_servers\"} * 100) / node_memory_MemTotal_bytes{job=\"Prod_servers\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"Prod_servers\", mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"Prod_servers\", mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Number of online containers",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{job=\"Prod_servers\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "skillbox.app container",
   "type": "stat",
   "description": "Status of main application",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{job=\"Prod_servers\",image=\"cr.yandex/crpf7vo008m7kcqbim40/skillbox:app\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"Prod_servers\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"Prod_servers\"} - node_boot_time_seconds{job=\"Prod_servers\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Prod_servers\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"Prod_servers\"}"
    }
   ]
  },
  { "title": "Detailed data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=\"Prod_servers\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',job=\"Prod_servers\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',job=\"Prod_servers\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",job=\"Prod_servers\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=\"Prod_servers\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"Prod_servers\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"Prod_servers\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"Prod_servers\"} - node_memory_MemFree_bytes{job=\"Prod_servers\"} - (node_memory_Cached_bytes{job=\"Prod_servers\"} + node_memory_Buffers_bytes{job=\"Prod_servers\"} + node_memory_SReclaimable_bytes{job=\"Prod_servers\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"Prod_servers\"} + node_memory_Buffers_bytes{job=\"Prod_servers\"} + node_memory_SReclaimable_bytes{job=\"Prod_servers\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"Prod_servers\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"Prod_servers\"} - node_memory_SwapFree_bytes{job=\"Prod_servers\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"Prod_servers\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"Prod_servers\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "CPU Usage by skillbox:app container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"Prod_servers\",image=\"cr.yandex/crpf7vo008m7kcqbim40/skillbox:app\"}[$__interval])) by (image) * 100",
     "legendFormat": "skillbox:app"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"Prod_servers\",image=~\".+\"}) by (image)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Skillbox http requests total",
   "type": "stat",
   "description": "The total number of processed requests",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skillbox_http_requests_total{job=\"Prod_servers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "skillbox.app container logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{host=\"prod-server\", image_name=\"cr.yandex/crpf7vo008m7kcqbim40/skillbox:app\"} |= ``"
    }
   ]
  },
  {
   "title": "Prod server syslog",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "{host=\"prod-server\", job=\"var_logs\", filename=\"/var/log/syslog\"} |= ``"
    }
   ]
  }
 ]
}