---

- name: Security Settings For Debian
  block:
    - name: Allow TCP Ports
      iptables:
        chain: INPUT
        rule_num: '1'
        action: insert
        protocol: tcp
        jump: ACCEPT
        destination_port: "{{ item }}"
      loop: [ '9093', '9094', '9099', '9100' ] # 9099 cAdvisor port, the default port (8080) is busy by main application
      # loop: [ '9090', '9093', '9094', '9099', '9100' ]
      # We dont use 9090 (Prometheus port) because reverse-proxy Nginx redirect requests

    - name: Allow UDP Ports
      iptables:
        chain: INPUT
        rule_num: '1'
        action: insert
        protocol: udp
        jump: ACCEPT
        destination_port: '9094'
  when:
    ansible_os_family == "Debian"
