---

docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb https://download.docker.com/linux/ubuntu focal stable"
packages:
  - git
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools