---

#- name: Creating Node Exporter Group
#  group: name="{{ groupId }}"
#  become: true

- name: Create Node Exporter User 
  user:
    name: "{{ userId }}"
    create_home: "no"
    system: yes
    shell: "/sbin/nologin"
    state: present

- name: Create directory for Node Exporter
  file:
    path: "/tmp/prometheus/node_exporter"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"

- name: Download And Unzipped Node Exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus/node_exporter"
#    creates: /tmp/prometheus/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64
    remote_src: yes

- name: Copy Bin File From Unzipped to Node Exporter
  copy: 
    src: /tmp/prometheus/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: "{{ userId }}"
    group: "{{ groupId }}"

- name: Create File for Node Exporter Systemd
  template:
    src=templates/node_exporter.service
    dest=/etc/systemd/system/
  notify:
    - systemd reload

- name: Systemctl Node Exporter Start
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    
- name: Check if Node Exporter emits metrics
  uri:
    url: http://127.0.0.1:9100/metrics
    method: GET
    status_code: 200
    
